version: '3.1'

services:
  backend:
    entrypoint: ["npm", "start"]
    build:
      context: ./ 
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    image: node:16.15-alpine
    restart: always
    ports:
      - "7070:7070"
    volumes:
      - ./:/opt
    working_dir: /opt