version: '3.1'

services:
  backend:
    entrypoint: ["npm", "start"]
    build:
      context: ./parloa 
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    image: node:16.15-alpine
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./parloa:/opt/parloa
    working_dir: /opt/parloa